"""Emit PGFPlots/TikZ figures from the same statistics the tables use.

Every coordinate is written by this module from the computed numbers, so no value
in a figure is transcribed by hand.  The files are regenerated by
``python3 scripts/paper_tables.py`` alongside the tables and macros.

Deliberately not matplotlib: this machine has no matplotlib, and the LaTeX
toolchain (pgfplots/tikz) is present, so figures are typeset natively and compile
straight into the paper with the same fonts as the body text.
"""

from __future__ import annotations

BANNER = "% GENERATED by scripts/paper/figures.py -- do not edit by hand.\n"


def _n(x: float, nd: int = 2) -> str:
    """A bare decimal pgfplots will parse (never nan/inf)."""
    if x is None or x != x:
        return "0"
    return f"{x:.{nd}f}"


def _wide(label: str) -> str:
    """Fault names contain underscores, which pgfplots would read as subscripts."""
    return label.replace("_", r"\_")


def _ticks(faults: list[str], labels: dict[str, str]) -> tuple[str, str]:
    """Return (ytick, yticklabels) as two separate key values.

    pgfplots runs every entry of `ytick' through pgfmath, so the tempting
    ``ytick={1/{DOM omission}}'' form makes it evaluate `DOM omission' as a
    function call and abort.  The label text belongs in `yticklabels', where it
    is typeset rather than parsed; braces keep spaces and commas intact.
    """
    yvals = ",".join(str(i) for i in range(1, len(faults) + 1))
    ylabs = ",".join("{" + _wide(labels[f]) + "}" for f in faults)
    return yvals, ylabs


def forest(stats_native: dict, faults: list[str], labels: dict[str, str]) -> str:
    """Paired risk difference with its bootstrap interval, one row per fault."""
    # Marks and error bars share ONE addplot: `\addplot' draws a connecting line by
    # default, so a separate error-bar plot would thread a polyline through the
    # estimates (which reads as a trend that does not exist).  `only marks' kills
    # the line but keeps both the marks and the explicitly requested error bars.
    marks = []
    for i, f in enumerate(faults, start=1):
        s = stats_native[f]
        d, lo, hi = s["delta_pp"], s["ci_lo"], s["ci_hi"]
        marks.append(f"({_n(d)},{i}) -= ({_n(d - lo)},0) += ({_n(hi - d)},0)")
    yvals, ylabs = _ticks(faults, labels)
    return BANNER + (
        "\\begin{figure}[t]\n\\centering\n"
        "\\begin{tikzpicture}\n"
        "\\begin{axis}[\n"
        # `width' is the axis rectangle only; the y tick labels hang outside it, so
        # \linewidth here overfulls the centred paragraph by ~18pt.  0.9 leaves room.
        "  width=0.9\\linewidth, height=5.2cm,\n"
        "  xlabel={$\\Delta$ (pp), fault $-$ control},\n"
        f"  ytick={{{yvals}}}, yticklabels={{{ylabs}}},\n"
        "  y dir=reverse, ymin=0.4, ymax=%d.6,\n" % len(faults) +
        "  xmin=-34, xmax=34, xtick={-30,-20,-10,0,10,20,30},\n"
        "  grid=major, grid style={gray!22},\n"
        "  tick label style={font=\\small}, label style={font=\\small},\n"
        "]\n"
        "\\draw[gray,dashed,thick] (axis cs:0,0.4) -- (axis cs:0,%d.6);\n" % len(faults) +
        # The error-bar keys go on the PLOT, not the axis: at axis level pgfplots
        # resolves `x dir' to its own axis-direction key (accepted values normal or
        # reverse), so the `.cd' prefix never applies and it is a hard error, not a
        # warning.  On a plot the documented `error bars/.cd' form works as intended.
        "\\addplot[only marks, mark=*, mark size=2.2pt, black,\n"
        "  error bars/.cd, x dir=both, x explicit]\n"
        f"  coordinates {{{' '.join(marks)}}};\n"
        "\\end{axis}\n"
        "\\end{tikzpicture}\n"
        "\\caption{Paired risk difference $\\Delta$ in official success (fault $-$ "
        "control) on native-evaluator pairs, with the percentile bootstrap interval "
        "over pair units. Every interval spans zero and no fault survives Holm "
        "correction, which is the paper's primary result. Compare "
        "Table~\\ref{tab:official_native}.}\n"
        "\\label{fig:forest}\n"
        "\\end{figure}\n"
    )


def behavior(beh: dict, faults: list[str], labels: dict[str, str]) -> str:
    """Within-pair process cost: ReAct steps and wall-clock seconds."""
    # xbar wants (value, category), not (category, value): with the pair the wrong way
    # round the bars are drawn from zero out to the row index and the category labels
    # collapse onto the value axis.
    xs = " ".join(f"({_n(beh[f]['step_median'],1)},{i})" for i, f in enumerate(faults, start=1))
    ts = " ".join(f"({_n(beh[f]['time_median'],1)},{i})" for i, f in enumerate(faults, start=1))
    yvals, ylabs = _ticks(faults, labels)
    common = (
        "  ytick={" + yvals + "}, y dir=reverse, ymin=0.4, ymax=" + f"{len(faults)}.6,\n"
        "  height=4.6cm,\n"
        "  tick label style={font=\\small}, label style={font=\\small},\n"
        "  nodes near coords, nodes near coords style={font=\\tiny},\n"
        # Row rules, so a bar in one panel is unambiguously matched to the label in
        # the other when the two panels sit side by side.
        "  ymajorgrids, grid style={gray!25},\n"
    )
    return BANNER + (
        "\\begin{figure}[t]\n\\centering\n"
        "\\begin{tikzpicture}\n"
        # Negative deltas are meaningful (a fault that makes the agent faster), so the
        # x range starts below zero instead of clipping those bars at an axis edge.
        # Labels go on the LEFT panel only: on the right panel they are drawn between
        # the two panels, straight over the left panel's bars.  The row rules make the
        # left-hand labels serve both.
        # `xbar' must precede the `nodes near coords' in `common': pgfplots decides
        # which coordinate the annotation carries from the plot type in force at the
        # time nodes near coords is read, and with the bar key still to come it labels
        # each bar with its row index instead of its value.
        "\\begin{axis}[name=steps, xbar, bar width=5pt,\n"
        "  width=0.40\\linewidth, xmin=-2, xmax=6,\n"
        + common +
        "  yticklabels={" + ylabs + "},\n"
        "  xlabel={$\\Delta$ steps (Hodges--Lehmann)},\n"
        "  fill=gray!60, draw=black!70,\n"
        "]\n"
        "\\draw[gray,dashed] (axis cs:0,0.4) -- (axis cs:0," + f"{len(faults)}.6);\n"
        f"\\addplot coordinates {{{xs}}};\n"
        "\\end{axis}\n"
        # `anchor=left' is not a pgf anchor ("No shape named `left'"), and the
        # `right of east' anchor form is not available here; east/west is enough.
        "\\begin{axis}[name=time, at={(steps.east)}, anchor=west, xshift=0.7cm,\n"
        "  xbar, bar width=5pt, width=0.40\\linewidth, xmin=-100, xmax=200,\n"
        + common +
        "  yticklabels={},\n"
        "  xlabel={$\\Delta$ time, s (Hodges--Lehmann)},\n"
        "  fill=gray!60, draw=black!70,\n"
        "]\n"
        "\\draw[gray,dashed] (axis cs:0,0.4) -- (axis cs:0," + f"{len(faults)}.6);\n"
        f"\\addplot coordinates {{{ts}}};\n"
        "\\end{axis}\n"
        "\\end{tikzpicture}\n"
        "\\caption{Within-pair process cost on the behavioural matrix. HTTP errors "
        "and parameter errors cost the agent steps and time, while DOM omission and "
        "popup blocking make it \\emph{faster} --- which we read as fault-induced "
        "early termination. All five are significant at $p<0.01$ except where noted "
        "in Table~\\ref{tab:behavior}.}\n"
        "\\label{fig:behavior}\n"
        "\\end{figure}\n"
    )


def noise_floor(ctrl_times: dict, faults: list[str], labels: dict[str, str]) -> str:
    """The five per-fault control arms share one configuration; their spread is the
    measurement floor below which no cross-arm cost comparison is interpretable."""
    lo = min(ctrl_times.values())
    hi = max(ctrl_times.values())
    # (value, category) and xbar: the faults belong on the category axis, seconds on
    # the value axis.  Built the other way round the five labels all land on the
    # value axis and print on top of each other.
    coords = " ".join(
        f"({_n(ctrl_times[f],1)},{i})" for i, f in enumerate(faults, start=1)
    )
    yvals, ylabs = _ticks(faults, labels)
    axis = (
        "\\begin{axis}[\n"
        "  width=0.8\\linewidth, height=4.4cm,\n"
        "  xbar, bar width=11pt, xmin=0, xmax=" + _n(hi * 1.16, 1) + ",\n"
        "  ytick={" + yvals + "}, y dir=reverse, ymin=0.4, ymax=" + f"{len(faults)}.6,\n"
        "  yticklabels={" + ylabs + "},\n"
        "  xlabel={mean wall-clock of the control arm, s},\n"
        "  tick label style={font=\\small}, label style={font=\\small},\n"
        "  nodes near coords, nodes near coords style={font=\\tiny},\n"
        "  fill=gray!55, draw=black!70,\n"
        "]\n"
        "\\addplot coordinates {" + coords + "};\n"
        "\\end{axis}\n"
    )
    return BANNER + (
        "\\begin{figure}[t]\n\\centering\n"
        "\\begin{tikzpicture}\n" + axis + "\\end{tikzpicture}\n"
        "\\caption{The noise floor. These five arms are the \\emph{same} agent "
        "configuration under the clean condition; each is the control half of one "
        f"fault's pair set. Their means span a factor of {_n(hi / lo, 2)}$\\times$, so "
        "absolute cross-arm timings are dominated by machine-level drift and only "
        "within-pair deltas are interpretable.}\n"
        "\\label{fig:noisefloor}\n"
        "\\end{figure}\n"
    )
