"""Compute the paper's statistics and emit LaTeX tables + macros.

Run from the repository root:

    python3 scripts/paper_tables.py

Outputs
-------
experiments/analysis/paper_v1/stats/*.csv   audit trail, one row per quantity
paper/iclr2027/tables/*.tex                 booktabs tables included by main.tex
paper/iclr2027/tables/macros.tex            every prose number as a macro
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

from . import datasets as ds
from . import figures as fg
from . import latex as tx
from . import stats_core as st

REPO = Path(__file__).resolve().parents[2]
EXP = REPO / "experiments" / "analysis"
PAPER = REPO / "paper" / "iclr2027"
OUT_STATS = EXP / "paper_v1" / "stats"
OUT_TABLES = PAPER / "tables"
OUT_FIGS = PAPER / "figures" / "tex"

BANNER = "% GENERATED by scripts/paper/make_tables.py -- do not edit by hand.\n"


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _csv(path: Path, header: list[str], rows: list[list]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        # Keep generated audit files stable across platforms and avoid CRLF
        # appearing as trailing whitespace in Git reviews.
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(header)
        w.writerows(rows)


# --------------------------------------------------------------------------
def fault_stats(cells: list[ds.PairedCell], fault: str) -> dict:
    sub = [c for c in cells if c.fault_type == fault]
    a, b, c, d = ds.concordance(sub)
    n = len(sub)
    pc = (a + b) / n if n else float("nan")
    pf = (a + c) / n if n else float("nan")
    deltas = [x.delta for x in sub]
    lo, hi, _, _ = st.bootstrap_delta(deltas)
    env_lo, env_hi = st.bootstrap_stability(deltas, seeds=(1, 7, 42, 2718, 31415), iters=4000)
    ci_lo, ci_hi = st.wilson_interval(a + b, n), st.wilson_interval(a + c, n)
    return {
        "fault": fault,
        "n_pairs": n,
        "a": a, "b": b, "c": c, "d": d,
        "discordant": b + c,
        "control_rate": pc, "fault_rate": pf,
        "delta_pp": 100 * (pf - pc),
        "ci_lo": 100 * lo, "ci_hi": 100 * hi,
        "env_lo": 100 * env_lo, "env_hi": 100 * env_hi,
        "ctl_ci": [100 * v for v in ci_lo],
        "flt_ci": [100 * v for v in ci_hi],
        "p_exact": st.mcnemar_exact(b, c),
        "p_midp": st.mcnemar_midp(b, c),
        "or": st.matched_odds_ratio(b, c),
        "or_haldane": st.or_haldane(b, c),
        "retention": st.success_retention(pc, pf),
        "cohen_h": st.cohen_h(pc, pf),
    }


def behavior_stats(pairs: list[ds.PairedCell], trials: list[ds.Trial], fault: str) -> dict:
    by_key = {(t.task_id, t.seed, t.condition): t for t in trials if t.fault_type == fault}
    dsteps, dtime = [], []
    for cell in pairs:
        if cell.fault_type != fault:
            continue
        c = by_key.get((cell.task_id, cell.seed, "control"))
        f = by_key.get((cell.task_id, cell.seed, "fault"))
        if c and f and c.steps is not None and f.steps is not None:
            dsteps.append(f.steps - c.steps)
            dtime.append((f.time_sec or 0) - (c.time_sec or 0))
    _, ns, ps = st.wilcoxon_signed_rank(dsteps)
    _, nt, pt = st.wilcoxon_signed_rank(dtime)
    return {
        "fault": fault,
        "n": len(dsteps),
        "step_mean": sum(dsteps) / len(dsteps) if dsteps else float("nan"),
        "step_median": st.hodges_lehmann(dsteps),
        "step_p": ps,
        "time_mean": sum(dtime) / len(dtime) if dtime else float("nan"),
        "time_median": st.hodges_lehmann(dtime),
        "time_p": pt,
    }


# --------------------------------------------------------------------------
def main() -> None:
    official_root = EXP / "official_subset_v1_final"
    matrix_root = EXP / "fault_matrices_v1"
    curated_root = REPO / "experiments" / "curated"
    arch_root = EXP / "architecture_gpt54_react_planexecute_v1"
    rec_root = EXP / "fault_subset_45"

    official = ds.load_official(official_root)
    cells_all = ds.build_pairs(official, dataset_layer="official_subset")
    cells_native = [c for c in cells_all if c.control_source == "native" and c.fault_source == "native"]

    matrix_trials, matrix_pairs = ds.load_matrix(matrix_root)
    baseline = ds.load_baseline(curated_root)
    arch = ds.load_architecture(arch_root)
    recovery = ds.load_recovery(rec_root)

    macros: list[tuple[str, str]] = []

    # ---------------- Table: dataset inventory ----------------------------
    nat = sum(1 for t in official if t.evaluation_source == "native")
    fb = sum(1 for t in official if t.evaluation_source == "fallback")
    base_nat = [r for r in baseline if not r.get("fallback_used")]
    base_fb = [r for r in baseline if r.get("fallback_used")]
    t1_rows = [
        ["Frozen ReAct control baseline", str(len(baseline)), "16 tasks $\\times$ 3 seeds",
         f"official; {sum(1 for r in baseline if r.get('official_success'))} success"],
        ["Behavioral fault matrix", str(len(matrix_trials)), "5 faults $\\times$ 16 tasks $\\times$ 5 seeds $\\times$ 2",
         "no HAR; behavioral only"],
        ["Official fault subset", str(len(official)), "5 faults $\\times$ 8 tasks $\\times$ 5 seeds $\\times$ 2",
         f"official; {sum(1 for t in official if t.official_success)} success"],
        ["Architecture pilot", str(len(arch)), "3 tasks $\\times$ 3 seeds $\\times$ 3 conditions $\\times$ 2 arch",
         "official; PILOT"],
        ["Recovery subset", str(len(recovery)), "5 faults $\\times$ 3 tasks $\\times$ 3 seeds",
         "log heuristics; subset of the official 400"],
    ]
    _write(OUT_TABLES / "T1_datasets.tex", BANNER + tx.booktabs(
        ["Dataset", "Records", "Design", "Evaluation"],
        t1_rows, "Committed experiment artifacts. Behavioral rows never enter an official-success denominator.",
        "tab:datasets", col_spec="lrrl", small=True))

    # ---------------- Table: baseline strata ------------------------------
    def stratum(rows: list[dict]) -> list[str]:
        n = len(rows)
        k = sum(1 for r in rows if r.get("official_success"))
        steps = [r["steps"] for r in rows if r.get("steps") is not None]
        times = [r["time_sec"] for r in rows if r.get("time_sec") is not None]
        return [
            str(n), str(k), tx.pct(k, n),
            f"{sum(steps) / len(steps):.2f}" if steps else "n/a",
            f"{sum(times) / len(times):.1f}" if times else "n/a",
        ]

    t2_rows = [["All trials"] + stratum(baseline),
               ["Native evaluator"] + stratum(base_nat),
               ["Fallback evaluator"] + stratum(base_fb)]
    _write(OUT_TABLES / "T2_baseline_strata.tex", BANNER + tx.booktabs(
        ["Stratum", "Trials", "Success", "Success rate", "Mean steps", "Mean time (s)"],
        t2_rows,
        "Frozen 48-trial ReAct baseline, stratified by evaluator path. Native and fallback rows are "
        "\\emph{not} comparable and must never be pooled; the pooled row is reported for completeness only.",
        "tab:baseline", small=True))
    macros += [
        ("BaseNativeN", str(len(base_nat))), ("BaseFallbackN", str(len(base_fb))),
        ("BaseNativeRate", tx.pct(sum(1 for r in base_nat if r.get("official_success")), len(base_nat))),
        ("BaseFallbackRate", tx.pct(sum(1 for r in base_fb if r.get("official_success")), len(base_fb))),
        ("BasePooledRate", tx.pct(sum(1 for r in baseline if r.get("official_success")), len(baseline))),
        ("BaselineSwing",
         f"{100 * (sum(1 for r in base_nat if r.get('official_success')) / len(base_nat) - sum(1 for r in baseline if r.get('official_success')) / len(baseline)):.1f}"),
    ]

    # ---------------- Table: official main result -------------------------
    stats_all = {f: fault_stats(cells_all, f) for f in ds.FAULTS_MAIN}
    stats_native = {f: fault_stats(cells_native, f) for f in ds.FAULTS_MAIN}

    # Marginal (per-arm) native rates: denominator is every native trial in that
    # arm, which is NOT the same subset as the pair-restricted rates above.
    marginal: dict[str, tuple[int, int, int, int]] = {}
    for f in ds.FAULTS_MAIN:
        ck = cn = fk = fn = 0
        for t in official:
            if t.fault_type != f or t.evaluation_source != "native":
                continue
            if t.condition == "control":
                cn += 1
                ck += int(t.official_success)
            else:
                fn += 1
                fk += int(t.official_success)
        marginal[f] = (ck, cn, fk, fn)

    def official_table(stats: dict, caption: str, label: str, with_marginal: bool = False) -> str:
        holm = st.holm_adjust([stats[f]["p_exact"] for f in ds.FAULTS_MAIN], ds.FAULTS_MAIN)
        holm_p = {lab: adj for lab, _, adj, _ in holm}
        rows = []
        for f in ds.FAULTS_MAIN:
            s = stats[f]
            row = [
                ds.FAULT_LABEL[f], str(s["n_pairs"]), str(s["discordant"]),
                tx.pct(s["a"] + s["b"], s["n_pairs"]), tx.pct(s["a"] + s["c"], s["n_pairs"]),
                tx.pp(s["delta_pp"]), tx.ci(s["ci_lo"], s["ci_hi"]),
                tx.pval(s["p_exact"]), tx.pval(s["p_midp"]), tx.pval(holm_p[f]),
                f"{s['or_haldane']:.2f}",
            ]
            if with_marginal:
                ck, cn, fk, fn = marginal[f]
                row[5:5] = [tx.pct(ck, cn), tx.pct(fk, fn)]
            rows.append(row)
        tot_a = sum(stats[f]["a"] for f in ds.FAULTS_MAIN)
        tot_b = sum(stats[f]["b"] for f in ds.FAULTS_MAIN)
        tot_c = sum(stats[f]["c"] for f in ds.FAULTS_MAIN)
        tot_d = sum(stats[f]["d"] for f in ds.FAULTS_MAIN)
        n = tot_a + tot_b + tot_c + tot_d
        pc, pf = (tot_a + tot_b) / n, (tot_a + tot_c) / n
        lo, hi, _, _ = st.bootstrap_delta(
            [c.delta for c in (cells_native if "native" in label else cells_all)])
        tot_row = [
            "\\textbf{All faults}", str(n), str(tot_b + tot_c),
            tx.pct(tot_a + tot_b, n), tx.pct(tot_a + tot_c, n),
            tx.pp(100 * (pf - pc)), tx.ci(100 * lo, 100 * hi),
            tx.pval(st.mcnemar_exact(tot_b, tot_c)), tx.pval(st.mcnemar_midp(tot_b, tot_c)),
            tx.pval(1.0), f"{st.or_haldane(tot_b, tot_c):.2f}",
        ]
        if with_marginal:
            ck = sum(marginal[f][0] for f in ds.FAULTS_MAIN)
            cn = sum(marginal[f][1] for f in ds.FAULTS_MAIN)
            fk = sum(marginal[f][2] for f in ds.FAULTS_MAIN)
            fn = sum(marginal[f][3] for f in ds.FAULTS_MAIN)
            tot_row[5:5] = [tx.pct(ck, cn), tx.pct(fk, fn)]
        rows.append(tot_row)

        header = ["Fault", "$n$", "Disc.", "Control", "Fault", "$\\Delta$ (pp)",
                  "95\\% CI (pp)", "$p_{\\text{exact}}$", "$p_{\\text{mid}}$",
                  "$p_{\\text{Holm}}$", "OR"]
        notes = ("$\\Delta$ is the paired risk difference (fault $-$ control); the interval is a "
                 "percentile bootstrap over pair units and is descriptive --- the exact McNemar "
                 "$p$ is the primary inferential quantity. OR is the Haldane-corrected matched odds ratio.")
        if with_marginal:
            header[5:5] = ["Control\\textsuperscript{\\S}", "Fault\\textsuperscript{\\S}"]
            notes += (" \\textsuperscript{\\S}Per-arm \\emph{marginal} native rate, whose denominator is "
                      "every native trial in that arm and therefore a \\emph{different subset} from the "
                      "pair-restricted rates in the Control/Fault columns. The two are not "
                      "interchangeable: the paired rates are the ones $\\Delta$ and the McNemar test refer to.")
        return tx.booktabs(header, rows, caption, label, small=True, notes=notes)

    _write(OUT_TABLES / "T3_official_all.tex", BANNER + official_table(
        stats_all,
        "Primary fault result, \\emph{all} evaluator paths pooled. Reported for completeness; the "
        "fallback adapter is structurally failure-biased (see Table~\\ref{tab:official_native}).",
        "tab:official_all"))
    _write(OUT_TABLES / "T4_official_native.tex", BANNER + official_table(
        stats_native,
        "Primary fault result on \\textbf{native-evaluator pairs only}. This is the table the paper "
        "relies on; the pooled version is contaminated by a fallback adapter that fails by construction. "
        "$n$ is below 40 because a pair is dropped when either arm was scored by the fallback adapter.",
        "tab:official_native", with_marginal=True))

    for f in ds.FAULTS_MAIN:
        key = "".join(w.capitalize() for w in f.split("_"))
        ck, cn, fk, fn = marginal[f]
        macros += [
            (f"Res{key}CtlMargNat", tx.pct(ck, cn)), (f"Res{key}FltMargNat", tx.pct(fk, fn)),
            (f"Res{key}CtlMargNatN", str(cn)), (f"Res{key}FltMargNatN", str(fn)),
        ]
    for tag, stats in (("", stats_all), ("Nat", stats_native)):
        for f in ds.FAULTS_MAIN:
            key = "".join(w.capitalize() for w in f.split("_"))
            s = stats[f]
            macros += [
                (f"Res{key}Delta{tag}", tx.pp(s["delta_pp"])),
                (f"Res{key}P{tag}", tx.pval(s["p_exact"])),
                (f"Res{key}Ctl{tag}", tx.pct(s["a"] + s["b"], s["n_pairs"])),
                (f"Res{key}Flt{tag}", tx.pct(s["a"] + s["c"], s["n_pairs"])),
                (f"Res{key}N{tag}", str(s["n_pairs"])),
                (f"Res{key}Disc{tag}", str(s["discordant"])),
            ]
    _, _b_all, _c_all, _ = ds.concordance(cells_all)
    _, _b_nat, _c_nat, _ = ds.concordance(cells_native)
    pi_d_all = (_b_all + _c_all) / len(cells_all)
    pi_d_nat = (_b_nat + _c_nat) / len(cells_native)
    macros += [
        ("OfficialN", str(len(official))),
        ("OfficialNativeN", str(nat)), ("OfficialFallbackN", str(fb)),
        ("OfficialNativePairs", str(len(cells_native))),
        ("OfficialAllPairs", str(len(cells_all))),
        ("MdePairedNForty", tx.num(st.mcnemar_mde(40, 0.20) * 100, 1)),
        ("MdePairedNEighty", tx.num(st.mcnemar_mde(80, 0.20) * 100, 1)),
        ("MdePairedNOneFiveFive", tx.num(st.mcnemar_mde(155, 0.20) * 100, 1)),
        ("PairsForTenPP", f"{st.mcnemar_n_required(0.10, 0.20):.0f}"),
        ("PiDAll", f"{pi_d_all:.3f}"), ("PiDNative", f"{pi_d_nat:.3f}"),
        ("PairsForTenPPObserved", f"{st.mcnemar_n_required(0.10, pi_d_nat):.0f}"),
        ("PairsForTenPPObservedAll", f"{st.mcnemar_n_required(0.10, pi_d_all):.0f}"),
    ]

    # ---------------- Table: behavior costs -------------------------------
    beh = {f: behavior_stats(matrix_pairs, matrix_trials, f) for f in ds.FAULTS_MAIN}
    b_rows = []
    for f in ds.FAULTS_MAIN:
        s = beh[f]
        b_rows.append([ds.FAULT_LABEL[f], str(s["n"]),
                       tx.pp(s["step_mean"], 2), tx.pp(s["step_median"], 1), tx.pval(s["step_p"]),
                       tx.pp(s["time_mean"], 1), tx.pp(s["time_median"], 1), tx.pval(s["time_p"])])
    _write(OUT_TABLES / "T5_behavior_costs.tex", BANNER + tx.booktabs(
        ["Fault", "$n$ pairs", "$\\Delta$ steps (mean)", "$\\Delta$ steps (HL)",
         "$p$", "$\\Delta$ time (s, mean)", "$\\Delta$ time (s, HL)", "$p$"],
        b_rows,
        "Paired behavioral cost from the behavioural matrix (\\MatrixPairs{} pairs, each logged twice). "
        "\\textbf{Behavior-only}: no HAR was "
        "retained, so no row carries an official success verdict. Deltas are within-pair (fault $-$ control); "
        "$p$ is the two-sided Wilcoxon signed-rank test.",
        "tab:behavior", small=True))

    for f in ds.FAULTS_MAIN:
        key = "".join(w.capitalize() for w in f.split("_"))
        bh = beh[f]
        macros += [
            (f"Beh{key}StepDelta", tx.pp(bh["step_mean"], 2)),
            (f"Beh{key}StepHL", tx.pp(bh["step_median"], 1)),
            (f"Beh{key}StepP", tx.pval(bh["step_p"])),
            (f"Beh{key}TimeDelta", tx.pp(bh["time_mean"], 1)),
            (f"Beh{key}TimeHL", tx.pp(bh["time_median"], 1)),
            (f"Beh{key}TimeP", tx.pval(bh["time_p"])),
            (f"Beh{key}N", str(bh["n"])),
        ]

    # noise floor: the five per-fault control arms share one configuration
    ctrl_times: dict[str, float] = {}
    for f in ds.FAULTS_MAIN:
        vals = [t.time_sec for t in matrix_trials if t.fault_type == f and t.condition == "control" and t.time_sec]
        ctrl_times[f] = sum(vals) / len(vals) if vals else float("nan")
    lo_f = min(ctrl_times.values()); hi_f = max(ctrl_times.values())
    macros += [
        ("NoiseFloorLo", f"{lo_f:.1f}"), ("NoiseFloorHi", f"{hi_f:.1f}"),
        ("NoiseFloorRatio", f"{hi_f / lo_f:.2f}"),
        ("ResHttpErrorStepDelta", tx.pp(beh["web_http_error"]["step_mean"], 2)),
        ("ResHttpErrorTimeDelta", tx.pp(beh["web_http_error"]["time_mean"], 1)),
        ("ResParamErrStepDelta", tx.pp(beh["agent_param_error"]["step_mean"], 2)),
    ]

    # ---------------- figures (PGFPlots/TikZ, same numbers as the tables) --
    _write(OUT_FIGS / "fig_forest.tex",
           fg.forest(stats_native, ds.FAULTS_MAIN, ds.FAULT_LABEL))
    _write(OUT_FIGS / "fig_behavior.tex",
           fg.behavior(beh, ds.FAULTS_MAIN, ds.FAULT_LABEL))
    _write(OUT_FIGS / "fig_noisefloor.tex",
           fg.noise_floor(ctrl_times, ds.FAULTS_MAIN, ds.FAULT_LABEL))

    # ---------------- Table: architecture pilot ---------------------------
    # Keyed by (architecture, condition, fault_type), NOT (architecture, condition).
    # The artifact's coarse ``condition`` column lumps all fault rows together, so
    # grouping on it alone silently pools web_dom_missing with web_http_error and
    # yields an 18-row "fault" cell that looks like a single condition.
    cells: dict[tuple, list[dict]] = {}
    for r in arch:
        cells.setdefault((r["architecture"], r["condition"], r["fault_type"]), []).append(r)
    t6_rows = []
    for (a, cond, ft), rows in sorted(cells.items()):
        n = len(rows); k = sum(1 for r in rows if r["official_success"])
        steps = [r["steps"] for r in rows if r["steps"] is not None]
        times = [r["time_sec"] for r in rows if r["time_sec"] is not None]
        calls = [r["llm_calls"] for r in rows if r["llm_calls"] is not None]
        label = "none (control)" if ft == "control" else ft
        t6_rows.append([a.replace("_", r"\_"), label.replace("_", r"\_"), str(n), f"{k}/{n}",
                        tx.pct(k, n), f"{sum(steps) / len(steps):.2f}" if steps else "n/a",
                        f"{sum(calls) / len(calls):.2f}" if calls else "n/a",
                        f"{sum(times) / len(times):.1f}" if times else "n/a"])
    n_arch_faults = len({ft for (_, _, ft) in cells if ft != "control"})
    _write(OUT_TABLES / "T6_architecture_pilot.tex", BANNER + tx.booktabs(
        ["Architecture", "Condition", "$n$", "Success", "Rate", "Steps", "LLM calls", "Time (s)"],
        t6_rows,
        "Architecture comparison --- \\textbf{PILOT, $n=9$ per cell}. Rows are broken out by fault; "
        "\\emph{not} by the artifact's coarse \\texttt{condition} column, which pools the "
        f"{n_arch_faults} injected faults into a single 18-row bucket. The committed "
        "\\texttt{run\\_architecture\\_matrix.py} does not reproduce these 54 rows (different task set and "
        "seed range), so this table supports no architecture ranking. The two architectures also differ "
        f"sharply in wall-clock (\\ArchReactTime{{}}~s vs \\ArchPlanTime{{}}~s on the control arm), which "
        "confounds any equal-budget comparison; the artifact records no per-role call counters, so budget "
        "equality cannot be verified.",
        "tab:architecture", small=True))
    pe_ctl = cells.get(("plan_execute", "control", "control"), [])
    re_ctl = cells.get(("react", "control", "control"), [])
    macros += [
        ("ArchReactCtl", tx.pct(sum(1 for r in re_ctl if r["official_success"]), len(re_ctl))),
        ("ArchPlanCtl", tx.pct(sum(1 for r in pe_ctl if r["official_success"]), len(pe_ctl))),
        ("ArchPlanTime", f"{sum(r['time_sec'] for r in pe_ctl) / len(pe_ctl):.1f}" if pe_ctl else "n/a"),
        ("ArchReactTime", f"{sum(r['time_sec'] for r in re_ctl) / len(re_ctl):.1f}" if re_ctl else "n/a"),
        ("ArchCellN", str(len(re_ctl))),
    ]

    # ---------------- Table: recovery -------------------------------------
    # The recovery artifact is degenerate.  Most of its flag columns are constant
    # across all 45 rows, ``recovered`` is row-for-row identical to
    # ``official_success``, and ``behavior_labels`` is a deterministic function of
    # ``recovered``.  Emitting counts for those columns would manufacture
    # evidence the data does not contain, so the table reports only the two
    # quantities that actually vary and names the rest as zero-information.
    rec_cols = [
        "observation_after_fault", "tool_changed", "retry_executed",
        "stale_action_repeated", "premature_stop", "goto_fallback", "plan_revised",
    ]
    degenerate = sorted(c for c in rec_cols
                        if len({str(r.get(c, "")) for r in recovery}) == 1)
    identical = all(str(r.get("recovered")).lower() == str(r.get("official_success")).lower()
                    for r in recovery)

    def _rec_ok(rows: list[dict]) -> int:
        return sum(1 for r in rows if str(r.get("official_success")).lower() == "true")

    def _rec_gf(rows: list[dict]) -> int:
        return sum(1 for r in rows if str(r.get("goto_fallback")).lower() == "true")

    rec_by_fault: dict[str, list[dict]] = {}
    for r in recovery:
        rec_by_fault.setdefault(r["fault_type"], []).append(r)
    t7_rows = []
    for f, rows in sorted(rec_by_fault.items()):
        n = len(rows)
        t7_rows.append([ds.FAULT_LABEL.get(f, f), str(n), f"{_rec_ok(rows)}/{n}",
                        tx.pct(_rec_ok(rows), n), f"{_rec_gf(rows)}/{n}"])
    t7_rows.append(["\\textbf{All faults}", str(len(recovery)),
                    f"{_rec_ok(recovery)}/{len(recovery)}",
                    tx.pct(_rec_ok(recovery), len(recovery)), f"{_rec_gf(recovery)}/{len(recovery)}"])
    _write(OUT_TABLES / "T7_recovery.tex", BANNER + tx.booktabs(
        ["Fault", "$n$", "Official success", "Rate", "\\texttt{goto\\_fallback}"],
        t7_rows,
        "The recovery artifact on its 45-trial subset. It is \\textbf{degenerate}: "
        + ", ".join("\\texttt{" + c.replace("_", r"\_") + "}" for c in degenerate)
        + " are constant across all 45 rows and therefore carry no information; "
        "\\texttt{plan\\_revised} was never recorded (empty, not false); and "
        + ("\\texttt{recovered} is row-for-row identical to \\texttt{official\\_success}"
           if identical else "\\texttt{recovered} differs from \\texttt{official\\_success}")
        + ". \\texttt{behavior\\_labels} is a deterministic function of \\texttt{recovered} "
        "(recovered $\\Rightarrow$ \\texttt{observation\\_refreshed}, otherwise "
        "\\texttt{fault\\_detected}), not an independent observation. Only the columns shown vary.",
        "tab:recovery", small=True))
    macros += [
        ("RecDegenerateCount", str(len(degenerate))),
        ("RecN", str(len(recovery))),
        ("RecSuccess", tx.pct(_rec_ok(recovery), len(recovery))),
        ("RecRecoveredIdentical", "true" if identical else "false"),
        ("RecGotoFallback", str(_rec_gf(recovery))),
    ]

    # ---------------- Table: power / MDE ----------------------------------
    def _mde(n: int, pi_d: float) -> str:
        m = st.mcnemar_mde(n, pi_d)
        # NaN here is informative: it means the design cannot reach 80% power even
        # for the largest effect the paired design can express (delta = pi_d).
        return "n/a" if m != m else f"{100 * m:.1f}"

    pm_rows = []
    for pi_d in (0.10, 0.15, 0.20, 0.25, 0.30):
        pm_rows.append([f"{pi_d:.2f}", _mde(31, pi_d), _mde(40, pi_d),
                        _mde(80, pi_d), _mde(155, pi_d)])
    _write(OUT_TABLES / "T8_power.tex", BANNER + tx.booktabs(
        ["Discordance $\\pi_d$", "MDE at $n=31$", "MDE at $n=40$",
         "MDE at $n=80$", "MDE at $n=155$"],
        pm_rows,
        "Minimum detectable paired difference in success rate (percentage points) at "
        "$\\alpha=\\Alpha{}$, power $\\Power{}$. \\textbf{n/a} means the design cannot reach the target "
        "power at \\emph{any} effect size the paired design can express (the risk difference is bounded by "
        "$\\pi_d$). The native-evaluator analysis has only $n=\\ResWebDomMissingNNat$--$\\ResWebTimeoutNNat$ "
        "pairs per fault. The $n=40$ column is therefore a counterfactual, and a null result under the "
        "actual design cannot be read as evidence of robustness.",
        "tab:power", small=True))

    # ---------------- CSVs -------------------------------------------------
    _csv(OUT_STATS / "official_paired_summary.csv",
         ["subset", "fault", "n_pairs", "a_both_pass", "b_control_only", "c_fault_only", "d_both_fail",
          "control_rate_paired", "fault_rate_paired", "control_rate_marginal_native",
          "fault_rate_marginal_native", "delta_pp", "boot_lo_pp", "boot_hi_pp",
          "boot_env_lo_pp", "boot_env_hi_pp", "p_exact", "p_midp", "or_haldane", "retention"],
         [[subset, s["fault"], s["n_pairs"], s["a"], s["b"], s["c"], s["d"],
           f"{s['control_rate']:.4f}", f"{s['fault_rate']:.4f}",
           f"{marginal[s['fault']][0] / marginal[s['fault']][1]:.4f}",
           f"{marginal[s['fault']][2] / marginal[s['fault']][3]:.4f}",
           f"{s['delta_pp']:.2f}",
           f"{s['ci_lo']:.2f}", f"{s['ci_hi']:.2f}", f"{s['env_lo']:.2f}", f"{s['env_hi']:.2f}",
           f"{s['p_exact']:.4f}", f"{s['p_midp']:.4f}", f"{s['or_haldane']:.3f}",
           f"{s['retention']:.3f}"]
          for subset, stats in (("pooled", stats_all), ("native_only", stats_native))
          for s in (stats[f] for f in ds.FAULTS_MAIN)])
    _csv(OUT_STATS / "behavior_costs.csv",
         ["fault", "n", "step_delta_mean", "step_delta_hl", "step_p", "time_delta_mean", "time_delta_hl", "time_p"],
         [[b["fault"], b["n"], f"{b['step_mean']:.3f}", f"{b['step_median']:.3f}", f"{b['step_p']:.5f}",
           f"{b['time_mean']:.2f}", f"{b['time_median']:.2f}", f"{b['time_p']:.5f}"]
          for b in (beh[f] for f in ds.FAULTS_MAIN)])
    _csv(OUT_STATS / "noise_floor.csv", ["fault", "control_mean_time_s"],
         [[f, f"{ctrl_times[f]:.2f}"] for f in ds.FAULTS_MAIN])
    _csv(OUT_STATS / "provenance.csv",
         ["dataset_layer", "source_file", "trials", "pairs", "evaluation", "in_official_denominator"],
         [["curated_baseline_control", "experiments/curated/gpt54_react_public16_control_v1.json",
           len(baseline), "", "official (native/fallback stratified)", "yes"],
          ["behavioral_matrix", "experiments/analysis/fault_matrices_v1/trials.json",
           len(matrix_trials), len(matrix_pairs), "NOT_EVALUATED_NO_HAR", "no"],
          ["official_subset",
           "official_subset_v1_final/official_trials.json + official_trial_audit.csv",
           len(official), len(cells_all), "official (native/fallback stratified)", "yes"],
          ["architecture_pilot", "architecture_gpt54_react_planexecute_v1/architecture_trial_results.csv",
           len(arch), "", "official", "yes"],
          ["recovery_subset", "fault_subset_45/fault_recovery_behavior.csv",
           len(recovery), "", "official subset of the frozen 400", "no (subset)"],
          ])

    # ---------------- macros ----------------------------------------------
    # Fixed experimental constants, so the prose cites them from one place.
    macros += [
        ("FaultCount", str(len(ds.FAULTS_MAIN))),
        ("TotalTrials", str(len(official) + len(matrix_trials) + len(baseline) + len(arch))),
        ("MaxSteps", "20"), ("TrialsPerCell", "5"), ("FaultSeed", "1"),
        ("FaultIntensity", "high"), ("FaultSeedCount", "1"),
        ("OfficialTasks", "8"), ("MatrixTasks", "16"), ("BaselineTasks", "16"),
        ("MatrixPairs", str(len(matrix_pairs))),
        ("ArchN", str(len(arch))), ("ArchTasks", "3"), ("ArchConditions", "3"),
        ("BaselineSeeds", "3"), ("BaselineN", str(len(baseline))),
        ("BootSeed", str(st.PAPER_BOOT_SEED)), ("BootIters", "20000"),
        ("Alpha", "0.05"), ("Power", "0.80"),
        ("ToolCount", "9"),
    ]
    _write(OUT_TABLES / "macros.tex", BANNER + tx.macro_block(macros))

    # ---------------- console summary -------------------------------------
    print("=== primary: native-only PAIRED (denominator = pairs with both arms native) ===")
    print(f"  {'fault':20s} {'n':>3s} {'disc':>4s}  {'paired ctl->flt':>17s}  "
          f"{'marginal native':>17s}  {'delta':>7s}  {'p_exact':>7s}")
    for f in ds.FAULTS_MAIN:
        s = stats_native[f]
        ck, cn, fk, fn = marginal[f]
        print(f"  {f:20s} {s['n_pairs']:3d} {s['discordant']:4d}  "
              f"{100 * s['control_rate']:6.1f}% ->{100 * s['fault_rate']:6.1f}%  "
              f"{100 * ck / cn:6.1f}% ->{100 * fk / fn:6.1f}%  "
              f"{s['delta_pp']:+6.1f}pp  {s['p_exact']:7.3f}")
    holm_all = st.holm_adjust([stats_native[f]["p_exact"] for f in ds.FAULTS_MAIN], ds.FAULTS_MAIN)
    print("  Holm-adjusted (native): " + ", ".join(f"{lab.split('_')[1]}={adj:.3f}" for lab, _, adj, _ in holm_all))
    print("=== sensitivity: pooled (fallback-contaminated, for audit only) ===")
    for f in ds.FAULTS_MAIN:
        s = stats_all[f]
        print(f"  {f:20s} n={s['n_pairs']:3d} {100 * s['control_rate']:5.1f}% -> "
              f"{100 * s['fault_rate']:5.1f}% delta={s['delta_pp']:+5.1f}pp p={s['p_exact']:.3f}")
    print("=== behavioral (400 pairs) ===")
    for f in ds.FAULTS_MAIN:
        b = beh[f]
        print(f"  {f:20s} steps {b['step_mean']:+5.2f} (p={b['step_p']:.4f})  "
              f"time {b['time_mean']:+7.1f}s (p={b['time_p']:.4f})")
    print(f"noise floor: control arms {lo_f:.1f}-{hi_f:.1f}s ratio {hi_f / lo_f:.2f}x")
    print(f"wrote tables to {OUT_TABLES}")


if __name__ == "__main__":
    main()
